version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: autorag_pg
    environment:
      POSTGRES_DB: ai
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
    ports:
      - "5532:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
